### ISSUE TITLE
Question about FileLock: deadlock when head on local?

### ISSUE THREAD

**Issue by qibin2020** [TingkaiLiu/Ray-SLURM-autoscaler#4]
Hi, I noticed when I deploy the head not under_slurm, the FileLock would get deadblock and stuck,
If I understand correctly, the filelock log shows two potential calls:
- `create_node()` is called from `autoscaler/_private/commands.py`, and it calls the `NodeProvider` then lunch the `head.sh` and wait and keep the lock
- in the `head.sh`, when new ray start head, the `autoscaler/_private/monitor.py` is activated and it creates the `StandardAutoscaler`. This is to update the resources info and monitor the autorescale request, but everytime it `reset()` (even when init), it will create the `NodeProvider` again inside, which cause loop and deadlock-ed

I am using ray 2.24.0. The related line might be:
https://github.com/TingkaiLiu/Ray-SLURM-autoscaler/blob/ad898c82320904d41a72a2b8f8d06a84a5eb6a1b/slurm/node_provider.py#L631
https://github.com/ray-project/ray/blob/82af058f3456dd7088b94a8d29a95450f73d215b/python/ray/autoscaler/_private/autoscaler.py#L251
https://github.com/ray-project/ray/blob/82af058f3456dd7088b94a8d29a95450f73d215b/python/ray/autoscaler/_private/autoscaler.py#L1066

I am not sure whether I mis-config sth and thank you so much for any suggestion or hint.

**Comment by TingkaiLiu** [comment]
Are you referring to the file lock used by the node_provider?

The scenario you described is exactly why the lock is needed. Multiple node_provider instances can exist, but only one of them should access the cluster state at a time. 

The `StandardAutoscaler` is started as a separate daemon thread, and would not block the node creation thread. 

You can check the autoscaler log using `/tmp/ray/session_latest/logs/monitor*`. If the log is printing and the status is updating, then it is not likely to be deadlock. You can also try to find any error message there.

**Comment by qibin2020** [comment]
Yes it seems I made the `ray start` blocked in the `head.sh` (so that before the main process release the lock, the newly started process try to acquire a same lock). I tried to use `&` to make subprocess return immediately and then everything runs well! (It may be caused by the delay of the NFS from myside)
Thank you for the reply and I close the issue.
